### ISSUE TITLE
dwmc crashes DWM

### ISSUE THREAD

**Issue by swindlesmccoop** [danielpza/dotfiles-old#1]
I'm using OpenBSD right now. I have patched DWM to be able to accept signals from OpenBSD, which it usually does just fine. However, trying to use `togglefloating` will outright exit DWM. It seems like it would be a crash since nothing else with dwmc does that, but I have no idea why this would occur.

**Comment by danielpza** [comment]
Hi @swindlesmccoop, I haven't used these dotfiles or dwm for a while now, sorry I don't think I can help you.

I noticed there was an update from Nihal Jere (fixed window titles not updating) perhaps they are able to help you.

Hope you figure it out.

Cheers.
